name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar_v2: ^6.1.0
  flutter_bloc: ^9.1.1
  persistent_bottom_nav_bar: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_carousel_widget: ^3.1.0
  meta: ^1.15.0
  bloc: ^9.0.0
  flutter_dash: ^1.0.0
  flutter_animate: ^4.5.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  iconsax: ^0.0.8
  google_sign_in: ^7.1.0
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^6.0.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  flutter_stripe: ^11.5.0
  flutter_svg: ^2.1.0
  flutter_credit_card: ^4.1.0
  font_awesome_flutter: ^10.8.0
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7+1
  build_runner: ^2.5.4
  flutter_screenutil: ^5.9.3
  google_generative_ai: ^0.4.7
  firebase_messaging: ^16.0.0
  cloud_functions: ^6.0.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  equatable: ^2.0.7
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  adaptive_theme: ^3.7.2
  flutter_dotenv: ^6.0.0
  package_info_plus: ^8.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
    - .env
